before_install:
  - python3 --version  # 3.5.2
  #- python3.6 --version || true  # fails to pyenv
  #- python3.7 --version || true  # fails to pyenv
  #- python3 -m pip --version || true
  #- python3 -m ensurepip || true
  #- python3 -m pip install --upgrade pip
  - python3 -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo -H python3
  - python3 -m pip --version
  - python3 -m pip install --user awscli
install: true
script:
  - aws version || true
  - aws -version || true
  - aws --version || true
