matrix:
  include:
     - dist: trusty
     - dist: xenial
     - dist: bionic

before_install:
  - python3 --version  # 3.5.2
  #- python3.6 --version || true  # fails to pyenv
  #- python3.7 --version || true  # fails to pyenv
  #- python3 -m pip --version || true
  #- python3 -m ensurepip || true
  #- python3 -m pip install --upgrade pip
  - python3 -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo -H python3
  - python3 -m pip --version  # pip 19.2.2 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
  - python3 -m pip install --user awscli
install: true
script: aws --version  # aws-cli/1.16.217 Python/3.5.2 Linux/4.15.0-1028-gcp botocore/1.12.207
